service: jamatic-graphql-poc-sp

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  apiGateway:
    shouldStartNameWithService: true

functions:
  graphql:
    handler: dist/server.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

plugins:
  - serverless-offline

# this exclude is specific to your system if your not on the same environment as Lambda
# this is added to decrease the output size to prevent size related issues
package:
  exclude:
    - 'node_modules/@prisma/cli/*-darwin'
    - 'node_modules/@prisma/cli/query-engine-*'
    - 'node_modules/.prisma/client/*-darwin'
    - 'node_modules/@prisma/engines/**'
    - 'src/**/*'
    - '*.eslint'

custom:
  serverless-offline:
    useChildProcesses: true
